# Generated by Django 2.2.19 on 2022-12-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221213_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(auto_created=True, unique=True, verbose_name='group_slug'),
        ),
    ]
